### ISSUE TITLE
Submissions?

### ISSUE THREAD

**Issue by act65** [distillpub/post--faq#1]
Hey, just curious.

Firstly, is this project of yours supposed to be 'the future' of academic publishing? Where research is accessible, free, fun to read, elegant, pretty, ... etc.  (or at least some middle ground between cutting-edge technical research and ?). I certainly hope so.

Secondly, do you guys plan to take/accept submissions? If so, what are your criteria for 'good' posts/articles?

Alex

**Comment by colah** [comment]
Hey Alex,

You have us figured out, but please don't spread our secret! :P

More seriously, yes, we are exploring a different approach to research communication and publishing, and we plan to accept submissions in the future. But we are still working out details and want to wait until we've figured things out before we talk about it too much or commit to plans. We should have more to say in a few weeks.

Chris

**Comment by act65** [comment]
Awesome!
